version: '3'

services:
  db:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - my-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - db
      - wordpress
    restart: always
    env_file:
      - .env
    networks:
      - my-network
    volumes:
      - wp_data:/var/www/html
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - my-network
  
  adminer:           image: dockette/adminer:full-php5           restart: always           ports:              - 8080:8080

networks:
  my-network:
    driver: bridge


volumes:
  db_data:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /Users/med-doba/Desktop/volumes/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/med-doba/Desktop/volumes/wp_data