version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql:rw
    networks:
      - my-network

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - my-network

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
      - adminer
    restart: always
    env_file:
      - .env
    networks:
      - my-network
    volumes:
      - wp_data:/var/www/html
      - web_data:/var/www/html/website

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    networks:
      - my-network

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    depends_on:
      - mariadb
    restart: always
    expose:
     - "9000"
    networks:
      - my-network

  website:
    container_name: website
    build: ./requirements/bonus/website
    restart: always
    volumes:
      - web_data:/app/website
    networks:
      - my-network

  mailhog:
    container_name: mailhog
    build: ./requirements/bonus/mailhog
    restart: always
    volumes:
      - wp_data:/var/www/html
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - my-network

  ftp_server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server
    restart: always
    ports:
      - '20:20'
      - '21:21'
      - '21100-21110:21100-21110'
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


volumes:
  db_data:
    driver: local
    driver_opts:
     type: none
     o: bind
     device: /home/med-doba/data/db_data
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/med-doba/data/wp_data
  web_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/med-doba/data/web_data
