version: '3'

services:
  web:
    build: ./requirements/nginx
    ports:
      -"443:443"
    depends_on:
      - db
  db:
    build: ./requirements/mariadb
    envirement:
      MYSQL_ROOT_PASSWORD: password