FROM debian:buster

RUN apt-get update && apt-get install -y git

RUN mkdir -p /app

WORKDIR /app

RUN rm -rf ./*

RUN git clone https://github.com/med-doba/StaticPortfolioWebsite.git website

CMD ["sleep", "1000000"]
