FROM debian:buster

RUN apt-get update && apt-get install -y git php7.3-fpm

RUN mkdir -p /run/php

RUN mkdir -p /app

WORKDIR /app

RUN rm -rf ./*

RUN git clone https://github.com/med-doba/StaticPortfolioWebsite.git website

CMD ["php-fpm7.3", "-F"]
