FROM debian:buster

RUN apt-get update && apt-get install -y curl php7.3-fpm php7.3-mysql

# RUN sed -i 's|^listen = .*$|listen = 0.0.0.0:9000|' /etc/php/7.3/fpm/pool.d/www.conf

RUN mkdir /adminer

WORKDIR /adminer

# RUN curl -o adminer.php https://www.adminer.org/latest.php
# RUN curl -L -O https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php

RUN curl -L -O https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php && mkdir -p /var/www/html && mv ./adminer-4.8.1.php /var/www/html/index.php
	# adduser -u 82 -D -S -G www-data www-data

# RUN mkdir -p /var/www/html
# RUN mv /adminer/adminer.php /var/www/html/index.php

RUN chown -R www-data:www-data /var/www/html

RUN mkdir -p /run/php

# COPY your-config-file.conf /etc/php/7.3/fpm/conf.d/your-config-file.conf
RUN sed -i 's|^listen = .*$|listen = 9000|' /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i 's|^User = .*$|User = www-data|' /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i 's|^Group = .*$|Group = www-data|' /etc/php/7.3/fpm/pool.d/www.conf
# RUN sed -i '/^Listen/s/.*/Listen 9000/' /etc/php/7.3/fpm/pool.d/www.conf
# RUN sed -i '/^User/s/.*/User www-data/' /etc/php/7.3/fpm/pool.d/www.conf
# RUN sed -i '/^Group/s/.*/Group www-data/' /etc/php/7.3/fpm/pool.d/www.conf

EXPOSE 9000
STOPSIGNAL SIGQUIT


CMD ["php-fpm7.3", "--nodaemonize"]
