FROM debian:buster

RUN apt-get update && apt-get install -y curl php7.3-fpm php7.3-mysql

RUN mkdir /adminer

WORKDIR /adminer

RUN curl -L -o adminer.php https://www.adminer.org/latest.php  && mkdir -p /var/www/html && mv ./adminer.php  /var/www/html/index.php

RUN chown -R www-data:www-data /var/www/html

RUN mkdir -p /run/php

RUN sed -i 's|^listen = .*$|listen = 9000|' /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i 's|^User = .*$|User = www-data|' /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i 's|^Group = .*$|Group = www-data|' /etc/php/7.3/fpm/pool.d/www.conf

EXPOSE 9000

CMD ["php-fpm7.3", "--nodaemonize"]
