FROM debian:buster

RUN apt-get update && apt-get install -y vsftpd

COPY ./conf/vsftpd.conf /etc/vsftpd.conf

COPY ./tools/ftp.sh .

RUN chmod +x ./ftp.sh

RUN mkdir -p /var/www/html

EXPOSE 20 21

CMD ["./ftp.sh"]
