FROM debian:buster

RUN apt-get update

RUN apt-get install -y vsftpd

# RUN sed -i 's|^listen=NO|listen=YES|' /etc/vsftpd.conf && sed -i 's|^listen_address=127.0.0.1|listen_address=127.0.0.1|' /etc/vsftpd.conf

COPY ./conf/vsftpd.conf /etc/vsftpd.conf

COPY ./tools/ftp.sh .

RUN chmod +x ./ftp.sh

RUN mkdir -p /var/www/html

EXPOSE 20 21

CMD ["./ftp.sh"]